name: Publish Studio (Nightly)
on:
  push:
    branches:
      - dev
jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # v4
      - name: Add pnpm
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org/"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Prepare
        run: pnpm dev:prepare
      - name: Build
        run: pnpm build
      - name: Release Nightly
        run: pnpm changelogen --bump --canary --publish --publishTag nightly
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
